version: 2

models:
  - name: avg_rating_change_by_eco
    description: "Average rating changes for black and white players over ECO opening"
    columns:
      - name: hash
        tests:
          - unique
          - not_null
 
